// <auto-generated />
using System;
using GuildManagerApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuildManagerApi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307124936_ScoringSettings_Indentity_Removal")]
    partial class ScoringSettings_Indentity_Removal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("GuildId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("WclActorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GuildId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WclActorId", "Server")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SlugName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Death Knight",
                            SlugName = "DeathKnight"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Druid",
                            SlugName = "Druid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hunter",
                            SlugName = "Hunter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mage",
                            SlugName = "Mage"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Monk",
                            SlugName = "Monk"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Paladin",
                            SlugName = "Paladin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Priest",
                            SlugName = "Priest"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rogue",
                            SlugName = "Rogue"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shaman",
                            SlugName = "Shaman"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Warlock",
                            SlugName = "Warlock"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Warrior",
                            SlugName = "Warrior"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Demon Hunter",
                            SlugName = "DemonHunter"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Evoker",
                            SlugName = "Evoker"
                        });
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Fight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<long>("EndTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int>("FightIndex")
                        .HasColumnType("integer");

                    b.Property<bool?>("Kill")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("character varying(16)");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("ReportId", "FightIndex")
                        .IsUnique();

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Region");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.PerformanceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<float?>("BestPercent")
                        .HasColumnType("real");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("FightId")
                        .HasColumnType("integer");

                    b.Property<float?>("RankPercent")
                        .HasColumnType("real");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("TotalParses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FightId");

                    b.HasIndex("FightId", "CharacterId")
                        .IsUnique();

                    b.ToTable("PerformanceEntries");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GuildId")
                        .HasColumnType("integer");

                    b.Property<string>("ImportError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ImportStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("ImportStatus");

                    b.HasIndex("StartTime");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.ScoringSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("scoring_settings", (string)null);
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.ScoringTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<float>("MaxPercent")
                        .HasColumnType("real");

                    b.Property<float>("MinPercent")
                        .HasColumnType("real");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("ScoringSettingsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScoringSettingsId");

                    b.HasIndex("ScoringSettingsId", "MinPercent")
                        .IsUnique();

                    b.ToTable("scoring_tiers", (string)null);
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SlugName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Name = "Blood",
                            SlugName = "Blood"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            Name = "Frost",
                            SlugName = "Frost"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            Name = "Unholy",
                            SlugName = "Unholy"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 2,
                            Name = "Balance",
                            SlugName = "Balance"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            Name = "Feral",
                            SlugName = "Feral"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 2,
                            Name = "Guardian",
                            SlugName = "Guardian"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            Name = "Restoration",
                            SlugName = "Restoration"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 3,
                            Name = "Beast Mastery",
                            SlugName = "BeastMastery"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 3,
                            Name = "Marksmanship",
                            SlugName = "Marksmanship"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 3,
                            Name = "Survival",
                            SlugName = "Survival"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 4,
                            Name = "Arcane",
                            SlugName = "Arcane"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 4,
                            Name = "Fire",
                            SlugName = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 4,
                            Name = "Frost",
                            SlugName = "Frost"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 5,
                            Name = "Brewmaster",
                            SlugName = "Brewmaster"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 5,
                            Name = "Mistweaver",
                            SlugName = "Mistweaver"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 5,
                            Name = "Windwalker",
                            SlugName = "Windwalker"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 6,
                            Name = "Holy",
                            SlugName = "Holy"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 6,
                            Name = "Protection",
                            SlugName = "Protection"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 6,
                            Name = "Retribution",
                            SlugName = "Retribution"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 7,
                            Name = "Discipline",
                            SlugName = "Discipline"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 7,
                            Name = "Holy",
                            SlugName = "Holy"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 7,
                            Name = "Shadow",
                            SlugName = "Shadow"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 8,
                            Name = "Assassination",
                            SlugName = "Assassination"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 8,
                            Name = "Subtlety",
                            SlugName = "Subtlety"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 8,
                            Name = "Outlaw",
                            SlugName = "Outlaw"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 9,
                            Name = "Elemental",
                            SlugName = "Elemental"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 9,
                            Name = "Enhancement",
                            SlugName = "Enhancement"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 9,
                            Name = "Restoration",
                            SlugName = "Restoration"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 10,
                            Name = "Affliction",
                            SlugName = "Affliction"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 10,
                            Name = "Demonology",
                            SlugName = "Demonology"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 10,
                            Name = "Destruction",
                            SlugName = "Destruction"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 11,
                            Name = "Arms",
                            SlugName = "Arms"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 11,
                            Name = "Fury",
                            SlugName = "Fury"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 11,
                            Name = "Protection",
                            SlugName = "Protection"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 12,
                            Name = "Havoc",
                            SlugName = "Havoc"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 12,
                            Name = "Vengeance",
                            SlugName = "Vengeance"
                        },
                        new
                        {
                            Id = 1,
                            ClassId = 13,
                            Name = "Devastation",
                            SlugName = "Devastation"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 13,
                            Name = "Preservation",
                            SlugName = "Preservation"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 13,
                            Name = "Augmentation",
                            SlugName = "Augmentation"
                        });
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.WclCredential", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ClientIdEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("wcl_credentials", (string)null);
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.WclUserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WclRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WclUserTokens");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Character", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GuildManagerApi.Domain.Entities.Guild", "Guild")
                        .WithMany("Characters")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GuildManagerApi.Domain.Entities.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Fight", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.Report", "Report")
                        .WithMany("Fights")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.PerformanceEntry", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.Character", "Character")
                        .WithMany("PerformanceEntries")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildManagerApi.Domain.Entities.Fight", "Fight")
                        .WithMany("PerformanceEntries")
                        .HasForeignKey("FightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Fight");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Report", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.Guild", "Guild")
                        .WithMany("Reports")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.ScoringTier", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.ScoringSettings", "ScoringSettings")
                        .WithMany("Tiers")
                        .HasForeignKey("ScoringSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringSettings");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Specialization", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.Class", "Class")
                        .WithMany("Specializations")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.WclUserToken", b =>
                {
                    b.HasOne("GuildManagerApi.Domain.Entities.AppUser", "User")
                        .WithOne("WclToken")
                        .HasForeignKey("GuildManagerApi.Domain.Entities.WclUserToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("WclToken");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Character", b =>
                {
                    b.Navigation("PerformanceEntries");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Class", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Fight", b =>
                {
                    b.Navigation("PerformanceEntries");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Guild", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Player", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.Report", b =>
                {
                    b.Navigation("Fights");
                });

            modelBuilder.Entity("GuildManagerApi.Domain.Entities.ScoringSettings", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
